apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: crisosilva88/k8s_project_database:1.1
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          name: mysql

        volumeMounts:
        - name: local
          mountPath: /var/lib/mysql/

      volumes:
      - name: local
        persistentVolumeClaim:
          claimName: local

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: crisosilva88/k8s_project_backend:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80




